# run in debug mode to emit more debugging information
debug: false

# Links to tools and references (optional)
tools:
  - name: LIDO-Schulung
    url: https://docs.nfdi4culture.de/lido-schulung
    description: Einführung in das LIDO-Format
  - name: LIDO2RDF
    path: /lido2rdf/
    proxy: http://localhost:5000/
    description: Convert LIDO XML to RDF
  - name: Cocoda
    url: https://coli-conc.gbv.de/cocoda/nfdi4objects/
    description: Mapping-Editor 
