# Get all named graphs with number of triples each

PREFIX schema: <http://schema.org/>

SELECT ?graph ?name (count(*) as ?triples) {
  GRAPH ?graph {?s ?p ?o}
  OPTIONAL { ?graph schema:name ?name }
} GROUP BY ?graph ?name ORDER BY DESC(?triples)
