# Get all named graphs with number of triples each

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?graph (count(*) as ?triples) {
  GRAPH ?graph {?s ?p ?o}
} GROUP BY ?graph ORDER BY DESC(?triples)
